# coding: utf-8

# flake8: noqa

"""
    Sumo Logic API

    # Getting Started Welcome to the Sumo Logic API reference. You can use these APIs to interact with the Sumo Logic platform. For information on the collector and search APIs see our [API home page](https://help.sumologic.com/APIs). ## API Endpoints Sumo Logic has several deployments in different geographic locations. You'll need to use the Sumo Logic API endpoint corresponding to your geographic location. See the table below for the different API endpoints by deployment. For details determining your account's deployment see [API endpoints](https://help.sumologic.com/?cid=3011). <table>   <tr>     <td> <strong>Deployment</strong> </td>     <td> <strong>Endpoint</strong> </td>   </tr> <tr>     <td> AU </td>     <td> https://api.au.sumologic.com/api/ </td>   </tr>   <tr>     <td> CA </td>     <td> https://api.ca.sumologic.com/api/ </td>   </tr> <tr>     <td> DE </td>     <td> https://api.de.sumologic.com/api/ </td>   </tr>   <tr>     <td> EU </td>     <td> https://api.eu.sumologic.com/api/ </td>   </tr>   <tr>     <td> JP </td>     <td> https://api.jp.sumologic.com/api/ </td>   </tr>   <tr>     <td> US1 </td>     <td> https://api.sumologic.com/api/ </td>   </tr>   <tr>     <td> US2 </td>     <td> https://api.us2.sumologic.com/api/ </td>   </tr> </table> ## Authentication Sumo Logic supports the following options for API authentication: - Access ID and Access Key - Base64 encoded Access ID and Access Key  See [Access Keys](https://help.sumologic.com/Manage/Security/Access-Keys) to generate an Access Key. Make sure to copy the key you create, because it is displayed only once. When you have an Access ID and Access Key you can execute requests such as the following:   ```bash   curl -u \"<accessId>:<accessKey>\" -X GET https://api.<deployment>.sumologic.com/api/v1/users   ```  Where `deployment` is either `au`, `ca`, `de`, `eu`, `jp`, `us1`, or `us2`. See [API endpoints](#section/API-Endpoints) for details.  If you prefer to use basic access authentication, you can do a Base64 encoding of your `<accessId>:<accessKey>` to authenticate your HTTPS request. The following is an example request, replace the placeholder `<encoded>` with your encoded Access ID and Access Key string:   ```bash   curl -H \"Authorization: Basic <encoded>\" -X GET https://api.<deployment>.sumologic.com/api/v1/users   ```   Refer to [API Authentication](https://help.sumologic.com/?cid=3012) for a Base64 example.  ## Status Codes Generic status codes that apply to all our APIs. See the [HTTP status code registry](https://www.iana.org/assignments/http-status-codes/http-status-codes.xhtml) for reference. <table>   <tr>     <td> <strong>HTTP Status Code</strong> </td>     <td> <strong>Error Code</strong> </td>     <td> <strong>Description</strong> </td>   </tr>   <tr>     <td> 301 </td>     <td> moved </td>     <td> The requested resource SHOULD be accessed through returned URI in Location Header.</td>   </tr>   <tr>     <td> 401 </td>     <td> unauthorized </td>     <td> Credential could not be verified. </td>   </tr>   <tr>     <td> 403 </td>     <td> forbidden </td>     <td> This operation is not allowed for your account type or the user doesn't have the role capability to perform this action. </td>   </tr>   <tr>     <td> 404 </td>     <td> notfound </td>     <td> Requested resource could not be found. </td>   </tr>   <tr>     <td> 405 </td>     <td> method.unsupported </td>     <td> Unsupported method for URL. </td>   </tr>   <tr>     <td> 415 </td>     <td> contenttype.invalid </td>     <td> Invalid content type. </td>   </tr>   <tr>     <td> 429 </td>     <td> rate.limit.exceeded </td>     <td> The API request rate is higher than 4 request per second or inflight API requests are higher than 10 request per second. </td>   </tr>   <tr>     <td> 500 </td>     <td> internal.error </td>     <td> Internal server error. </td>   </tr>   <tr>     <td> 503 </td>     <td> service.unavailable </td>     <td> Service is currently unavailable. </td>   </tr> </table> ## Filtering Some API endpoints support filtering results on a specified set of fields. Each endpoint that supports filtering will list the fields that can be filtered. Multiple fields can be combined by using an ampersand `&` character.  For example, to get 20 users whose `firstName` is `John` and `lastName` is `Doe`:   ```bash   api.sumologic.com/v1/users?limit=20&firstName=John&lastName=Doe   ```  ## Sorting Some API endpoints support sorting fields by using the `sortBy` query parameter. The default sort order is ascending. Prefix the field with a minus sign `-` to sort in descending order.  For example, to get 20 users sorted by their `email` in descending order:   ```bash   api.sumologic.com/v1/users?limit=20&sort=-email   ```  ## Rate Limiting * A rate limit of four API requests per second (240 requests per minute) applies to all API calls from a user. * A rate limit of 10 concurrent requests to any API endpoint applies to an access key.  If a rate is exceeded, a rate limit exceeded 429 status code is returned.  ## Generating Clients You can use [OpenAPI Generator](https://openapi-generator.tech) to generate clients from the YAML file to access the API.  ### Using [NPM](https://www.npmjs.com/get-npm) 1. Install [NPM package wrapper](https://github.com/openapitools/openapi-generator-cli) globally, exposing the CLI   on the command line:   ```bash   npm install @openapitools/openapi-generator-cli -g   ```   You can see detailed instructions [here](https://openapi-generator.tech/docs/installation#npm).  2. Download the [YAML file](/docs/sumologic-api.yaml) and save it locally. Let's say the file is saved as `sumologic-api.yaml`. 3. Use the following command to generate `python` client inside the `sumo/client/python` directory:   ```bash   openapi-generator generate -i sumologic-api.yaml -g python -o sumo/client/python   ```   ### Using [Homebrew](https://brew.sh/) 1. Install OpenAPI Generator   ```bash   brew install openapi-generator   ```  2. Download the [YAML file](/docs/sumologic-api.yaml) and save it locally. Let's say the file is saved as `sumologic-api.yaml`. 3. Use the following command to generate `python` client side code inside the `sumo/client/python` directory:   ```bash   openapi-generator generate -i sumologic-api.yaml -g python -o sumo/client/python   ```   # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

# import apis into sdk package
from swagger_client.api.connection_management_api import ConnectionManagementApi
from swagger_client.api.content_management_api import ContentManagementApi
from swagger_client.api.content_permissions_api import ContentPermissionsApi
from swagger_client.api.extraction_rule_management_api import ExtractionRuleManagementApi
from swagger_client.api.folder_management_api import FolderManagementApi
from swagger_client.api.ingest_budget_management_v1_api import IngestBudgetManagementV1Api
from swagger_client.api.metrics_alert_monitor_management_api import MetricsAlertMonitorManagementApi
from swagger_client.api.partition_management_api import PartitionManagementApi
from swagger_client.api.role_management_api import RoleManagementApi
from swagger_client.api.rules_library_management_api import RulesLibraryManagementApi
from swagger_client.api.scheduled_view_management_api import ScheduledViewManagementApi
from swagger_client.api.user_management_api import UserManagementApi
# import ApiClient
from swagger_client.api_client import ApiClient
from swagger_client.configuration import Configuration
# import models into sdk package
from swagger_client.models.action import Action
from swagger_client.models.aggregation import Aggregation
from swagger_client.models.alert_search_notification_sync_definition import AlertSearchNotificationSyncDefinition
from swagger_client.models.async_job_status import AsyncJobStatus
from swagger_client.models.auto_complete_value_sync_definition import AutoCompleteValueSyncDefinition
from swagger_client.models.begin_async_job_response import BeginAsyncJobResponse
from swagger_client.models.begin_bounded_time_range import BeginBoundedTimeRange
from swagger_client.models.bulk_async_status_response import BulkAsyncStatusResponse
from swagger_client.models.bulk_begin_async_job_response import BulkBeginAsyncJobResponse
from swagger_client.models.bulk_error_response import BulkErrorResponse
from swagger_client.models.change_email_request import ChangeEmailRequest
from swagger_client.models.collector_identity import CollectorIdentity
from swagger_client.models.coloring_rule import ColoringRule
from swagger_client.models.coloring_threshold import ColoringThreshold
from swagger_client.models.complete_literal_time_range import CompleteLiteralTimeRange
from swagger_client.models.connection import Connection
from swagger_client.models.connection_definition import ConnectionDefinition
from swagger_client.models.container_panel import ContainerPanel
from swagger_client.models.content import Content
from swagger_client.models.content_copy_params import ContentCopyParams
from swagger_client.models.content_list import ContentList
from swagger_client.models.content_permission_assignment import ContentPermissionAssignment
from swagger_client.models.content_permission_result import ContentPermissionResult
from swagger_client.models.content_permission_update_request import ContentPermissionUpdateRequest
from swagger_client.models.content_sync_definition import ContentSyncDefinition
from swagger_client.models.create_investigation_action import CreateInvestigationAction
from swagger_client.models.create_partition_definition import CreatePartitionDefinition
from swagger_client.models.create_role_definition import CreateRoleDefinition
from swagger_client.models.create_scheduled_view_definition import CreateScheduledViewDefinition
from swagger_client.models.create_user_definition import CreateUserDefinition
from swagger_client.models.csv_variable_source_definition import CsvVariableSourceDefinition
from swagger_client.models.dashboard_sync_definition import DashboardSyncDefinition
from swagger_client.models.email_action import EmailAction
from swagger_client.models.email_search_notification_sync_definition import EmailSearchNotificationSyncDefinition
from swagger_client.models.epoch_time_range_boundary import EpochTimeRangeBoundary
from swagger_client.models.error_description import ErrorDescription
from swagger_client.models.error_response import ErrorResponse
from swagger_client.models.exportable_lookup_table_info import ExportableLookupTableInfo
from swagger_client.models.extraction_rule import ExtractionRule
from swagger_client.models.extraction_rule_definition import ExtractionRuleDefinition
from swagger_client.models.field_value_tuple import FieldValueTuple
from swagger_client.models.filter import Filter
from swagger_client.models.folder import Folder
from swagger_client.models.folder_definition import FolderDefinition
from swagger_client.models.folder_sync_definition import FolderSyncDefinition
from swagger_client.models.grid import Grid
from swagger_client.models.header import Header
from swagger_client.models.id_array import IdArray
from swagger_client.models.id_to_rules_library_base_response_map import IdToRulesLibraryBaseResponseMap
from swagger_client.models.ingest_budget import IngestBudget
from swagger_client.models.ingest_budget_definition import IngestBudgetDefinition
from swagger_client.models.iso8601_time_range_boundary import Iso8601TimeRangeBoundary
from swagger_client.models.layout import Layout
from swagger_client.models.layout_structure import LayoutStructure
from swagger_client.models.list_collector_identities_response import ListCollectorIdentitiesResponse
from swagger_client.models.list_connections_response import ListConnectionsResponse
from swagger_client.models.list_extraction_rules_response import ListExtractionRulesResponse
from swagger_client.models.list_ingest_budgets_response import ListIngestBudgetsResponse
from swagger_client.models.list_partitions_response import ListPartitionsResponse
from swagger_client.models.list_role_models_response import ListRoleModelsResponse
from swagger_client.models.list_rules_library_base_response import ListRulesLibraryBaseResponse
from swagger_client.models.list_scheduled_views_response import ListScheduledViewsResponse
from swagger_client.models.list_user_models_response import ListUserModelsResponse
from swagger_client.models.literal_time_range_boundary import LiteralTimeRangeBoundary
from swagger_client.models.local_variable import LocalVariable
from swagger_client.models.log_query_variable_source_definition import LogQueryVariableSourceDefinition
from swagger_client.models.lookup_table_field import LookupTableField
from swagger_client.models.lookup_table_sync_definition import LookupTableSyncDefinition
from swagger_client.models.magellan_metadata_variable_source_definition import MagellanMetadataVariableSourceDefinition
from swagger_client.models.metadata_model import MetadataModel
from swagger_client.models.metadata_with_user_info import MetadataWithUserInfo
from swagger_client.models.metrics_alert_query import MetricsAlertQuery
from swagger_client.models.metrics_filter import MetricsFilter
from swagger_client.models.metrics_monitor_data_in_range_rule import MetricsMonitorDataInRangeRule
from swagger_client.models.metrics_monitor_definition import MetricsMonitorDefinition
from swagger_client.models.metrics_monitor_instance import MetricsMonitorInstance
from swagger_client.models.metrics_monitor_missing_data_rule import MetricsMonitorMissingDataRule
from swagger_client.models.metrics_monitor_mute_status import MetricsMonitorMuteStatus
from swagger_client.models.metrics_monitor_rule import MetricsMonitorRule
from swagger_client.models.metrics_monitor_rule_email_notification import MetricsMonitorRuleEmailNotification
from swagger_client.models.metrics_monitor_rule_time_threshold import MetricsMonitorRuleTimeThreshold
from swagger_client.models.metrics_monitor_rule_webhook_notification import MetricsMonitorRuleWebhookNotification
from swagger_client.models.metrics_monitors_response import MetricsMonitorsResponse
from swagger_client.models.metrics_query_data import MetricsQueryData
from swagger_client.models.metrics_query_sync_definition import MetricsQuerySyncDefinition
from swagger_client.models.metrics_query_variable_source_definition import MetricsQueryVariableSourceDefinition
from swagger_client.models.metrics_saved_search_query_sync_definition import MetricsSavedSearchQuerySyncDefinition
from swagger_client.models.metrics_saved_search_sync_definition import MetricsSavedSearchSyncDefinition
from swagger_client.models.mewboard_sync_definition import MewboardSyncDefinition
from swagger_client.models.named_action import NamedAction
from swagger_client.models.named_connection_action import NamedConnectionAction
from swagger_client.models.notable_event_action import NotableEventAction
from swagger_client.models.notable_event_field import NotableEventField
from swagger_client.models.notification_threshold_sync_definition import NotificationThresholdSyncDefinition
from swagger_client.models.on_time_interval_actions import OnTimeIntervalActions
from swagger_client.models.panel import Panel
from swagger_client.models.parameter_auto_complete_sync_definition import ParameterAutoCompleteSyncDefinition
from swagger_client.models.partition import Partition
from swagger_client.models.path import Path
from swagger_client.models.path_item import PathItem
from swagger_client.models.query import Query
from swagger_client.models.query_parameter_sync_definition import QueryParameterSyncDefinition
from swagger_client.models.relative_time_range_boundary import RelativeTimeRangeBoundary
from swagger_client.models.remove_lookup_table_row_action import RemoveLookupTableRowAction
from swagger_client.models.repeating_panel import RepeatingPanel
from swagger_client.models.report_filter_sync_definition import ReportFilterSyncDefinition
from swagger_client.models.report_panel_sync_definition import ReportPanelSyncDefinition
from swagger_client.models.resolvable_time_range import ResolvableTimeRange
from swagger_client.models.role_model import RoleModel
from swagger_client.models.rule_actions import RuleActions
from swagger_client.models.rule_item import RuleItem
from swagger_client.models.rule_warnings import RuleWarnings
from swagger_client.models.rules_library_base import RulesLibraryBase
from swagger_client.models.rules_library_base_response import RulesLibraryBaseResponse
from swagger_client.models.rules_library_base_update import RulesLibraryBaseUpdate
from swagger_client.models.rules_library_export_base import RulesLibraryExportBase
from swagger_client.models.rules_library_folder import RulesLibraryFolder
from swagger_client.models.rules_library_folder_export import RulesLibraryFolderExport
from swagger_client.models.rules_library_folder_response import RulesLibraryFolderResponse
from swagger_client.models.rules_library_folder_update import RulesLibraryFolderUpdate
from swagger_client.models.rules_library_rule import RulesLibraryRule
from swagger_client.models.rules_library_rule_export import RulesLibraryRuleExport
from swagger_client.models.rules_library_rule_response import RulesLibraryRuleResponse
from swagger_client.models.rules_library_rule_update import RulesLibraryRuleUpdate
from swagger_client.models.save_to_view_notification_sync_definition import SaveToViewNotificationSyncDefinition
from swagger_client.models.saved_search_sync_definition import SavedSearchSyncDefinition
from swagger_client.models.saved_search_with_schedule_sync_definition import SavedSearchWithScheduleSyncDefinition
from swagger_client.models.schedule_notification_sync_definition import ScheduleNotificationSyncDefinition
from swagger_client.models.schedule_search_parameter_sync_definition import ScheduleSearchParameterSyncDefinition
from swagger_client.models.scheduled_view import ScheduledView
from swagger_client.models.search_schedule_sync_definition import SearchScheduleSyncDefinition
from swagger_client.models.service_now_connection import ServiceNowConnection
from swagger_client.models.service_now_definition import ServiceNowDefinition
from swagger_client.models.service_now_fields_sync_definition import ServiceNowFieldsSyncDefinition
from swagger_client.models.service_now_search_notification_sync_definition import ServiceNowSearchNotificationSyncDefinition
from swagger_client.models.sumo_search_panel import SumoSearchPanel
from swagger_client.models.test_connection_response import TestConnectionResponse
from swagger_client.models.text_panel import TextPanel
from swagger_client.models.time_range_boundary import TimeRangeBoundary
from swagger_client.models.topology_label_map import TopologyLabelMap
from swagger_client.models.topology_label_values_list import TopologyLabelValuesList
from swagger_client.models.topology_search_label import TopologySearchLabel
from swagger_client.models.update_folder_request import UpdateFolderRequest
from swagger_client.models.update_lookup_table_row_action import UpdateLookupTableRowAction
from swagger_client.models.update_partition_definition import UpdatePartitionDefinition
from swagger_client.models.update_role_definition import UpdateRoleDefinition
from swagger_client.models.update_scheduled_view_definition import UpdateScheduledViewDefinition
from swagger_client.models.update_user_definition import UpdateUserDefinition
from swagger_client.models.user_info import UserInfo
from swagger_client.models.user_model import UserModel
from swagger_client.models.variable import Variable
from swagger_client.models.variable_source_definition import VariableSourceDefinition
from swagger_client.models.variable_values_log_query_request import VariableValuesLogQueryRequest
from swagger_client.models.variables_values_data import VariablesValuesData
from swagger_client.models.webhook_connection import WebhookConnection
from swagger_client.models.webhook_definition import WebhookDefinition
from swagger_client.models.webhook_header import WebhookHeader
from swagger_client.models.webhook_post_action import WebhookPostAction
from swagger_client.models.webhook_search_notification_sync_definition import WebhookSearchNotificationSyncDefinition
